ambari_base_url: "http://public-repo-1.hortonworks.com/ambari"
  
ambari_version: "2.2.0.0"
ambari_major_version: "2.x"
ambari_repos: 
  RHEL: 
    url: "{{ambari_base_url}}/centos{{ ansible_distribution_major_version }}/{{ ambari_major_version }}/updates/{{ ambari_version }}/ambari.repo"
    gpg_key_url: "{{ ambari_base_url }}/centos{{ ansible_distribution_major_version }}/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"

  Debian: 
    url: "{{ ambari_base_url }}/{{ ansible_distribution | lower }}{{ansible_distribution_major_version}}/{{ambari_major_version}}/updates/{{ambari_version}}/ambari.list"
    keyserver: keyserver.ubuntu.com
    key: "B9733A7A07513CAD"

