---
- name: Include RedHat specific setup
  include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian specific setup
  include: Debian.yml
  when: ansible_os_family == "Debian"


- name: Include setup with mysql
  include: mysql.yml
  when: ( ambari_installed|changed or ambari_server_force_configuration ) and ambari_db_flavour == "mysql"

- name: "Ensure db flavour is mysql(the only supported)"
  fail: msg="other db flavours than mysql are not yet implemented"
  when: ambari_db_flavour != "mysql"

# - name : Create folder
#  file : dest=/opt/ambari-install state=directory mode=0755

# - name : check if ambari-server is installed
#  wait_for : path=/tmp/ambari-install-output search_regex="completed successfully"

#- name: Check for ambari-server status (workaround for invalid service ambari status code)
#  command: ambari-server status
#  changed_when: False
#  register: ambaristatus
#
#- name: Set ambari_server_not_running variable
#  set_fact:
#    ambari_server_not_running: "{{ ambaristatus.stdout | search('.*Ambari Server not running.*') }}"

- name : start ambari server and enabled at reboot
  service : 
    name: ambari-server 
    state: "{{  ambari_server_force_restart or ambari_server_force_configuration | ternary('restarted', 'started') }}"
    enabled: yes
  register: ambari_up

- name : check if ambari-server is up
  wait_for : port={{ ambari_server_port }} delay=10
