---
- name: "Debian specific steps"
  when: ansible_os_family == "Debian"
  include: "Debian.yml"

- name: "RedHat specific steps"
  when: ansible_os_family == "RedHat"
  include: "RedHat.yml"

- name: Configure ambari-server hostname in ambari-agent configuration
  ini_file: 
   dest: /etc/ambari-agent/conf/ambari-agent.ini
   section: server
   option: hostname
   value: "{{ambari_server_hostname}}"
   backup: yes

- name: Ensure ambari-agent is running and enabled
  service: name=ambari-agent state={{ambari_agent_force_restart | ternary('restarted', 'started') }}  enabled=yes

- name : wait for agent to register
  wait_for: port=8670
